// Intent: expose stable SDK API surface for scanners and integrators.
// TODO(cloudburn): stabilize API before first public release.
export { awsCorePreset } from '@cloudburn/rules';
export { builtInRuleMetadata } from './built-in-rules.js';
export { parseIaC } from './parsers/index.js';
export { assertSupportedAwsRegion, assertValidAwsRegion } from './providers/aws/client.js';
export { isAwsDiscoveryErrorCode } from './providers/aws/errors.js';
export { CloudBurnClient } from './scanner.js';
export type {
  AwsApiGatewayStage,
  AwsCloudFrontDistribution,
  AwsCloudTrailTrail,
  AwsCloudWatchLogGroup,
  AwsCloudWatchLogStream,
  AwsCostUsage,
  AwsDiscoveredResource,
  AwsDiscoveryCatalog,
  AwsDiscoveryInitialization,
  AwsDiscoveryRegion,
  AwsDiscoveryRegionStatus,
  AwsDiscoveryStatus,
  AwsDiscoveryTarget,
  AwsDynamoDbAutoscaling,
  AwsDynamoDbTable,
  AwsEbsSnapshot,
  AwsEbsVolume,
  AwsEc2Instance,
  AwsEc2LoadBalancer,
  AwsEc2ReservedInstance,
  AwsEc2TargetGroup,
  AwsEcsCluster,
  AwsEcsClusterMetric,
  AwsEcsContainerInstance,
  AwsEcsService,
  AwsEcsServiceAutoscaling,
  AwsEksNodegroup,
  AwsElastiCacheCluster,
  AwsElastiCacheReservedNode,
  AwsEmrCluster,
  AwsEmrClusterMetric,
  AwsLambdaFunction,
  AwsLambdaFunctionMetric,
  AwsRdsInstance,
  AwsRdsInstanceActivity,
  AwsRdsInstanceCpuMetric,
  AwsRdsReservedInstance,
  AwsRdsSnapshot,
  AwsRedshiftCluster,
  AwsRedshiftClusterMetric,
  AwsRedshiftReservedNode,
  AwsRegion,
  AwsRoute53HealthCheck,
  AwsRoute53Record,
  AwsRoute53Zone,
  AwsSageMakerEndpointActivity,
  AwsSageMakerNotebookInstance,
  AwsSecretsManagerSecret,
  AwsSupportedResourceType,
  BuiltInRuleMetadata,
  CloudBurnConfig,
  CloudBurnModeConfig,
  CloudProvider,
  ConfigOutputFormat,
  Finding,
  FindingMatch,
  ProviderFindingGroup,
  RegisteredRules,
  Rule,
  RuleConfig,
  ScanDiagnostic,
  ScanResult,
  ScanSource,
  Source,
  SourceLocation,
} from './types.js';
