export {
  createApiGatewayClient,
  createCloudFrontClient,
  createCloudTrailClient,
  createCloudWatchClient,
  createCloudWatchLogsClient,
  createCostExplorerClient,
  createDynamoDbClient,
  createEc2Client,
  createEcrClient,
  createElastiCacheClient,
  createEmrClient,
  createLambdaClient,
  createRedshiftClient,
  createResourceExplorerClient,
  createRoute53Client,
  createSecretsManagerClient,
  listEnabledAwsRegions,
  resolveAwsAccountId,
  resolveCurrentAwsRegion,
} from './client.js';
export {
  discoverAwsResources,
  initializeAwsDiscovery,
  listSupportedAwsResourceTypes,
} from './discovery.js';
