// Intent: expose rule packs, presets, and metadata contracts for SDK and users.
// TODO(cloudburn): publish stable docs for custom rule pack authoring.

export {
  AWS_CONFIG_RECORDING_FREQUENCY_MINIMUM_SAVINGS_USD,
  createAwsConfigRecordingFrequencyImpact,
} from './aws/config/recording-frequency.js';
export { createAwsCostOptimizationHubFindingMatch } from './aws/costoptimizationhub/finding.js';
export { awsRules } from './aws/index.js';
export { canonicalizeAwsResourceId, getAwsArnScope } from './aws/resource-identity.js';
export { azureRules } from './azure/index.js';
export { gcpRules } from './gcp/index.js';
export { awsCorePreset } from './presets/aws-core.js';
export type { AwsCapability } from './shared/capabilities.js';
export {
  AWS_CAPABILITIES,
  getAwsDatasetCapability,
  getAwsRuleCapabilities,
} from './shared/capabilities.js';
export {
  createFinding,
  createFindingMatch,
  createLiveEvaluationCoverage,
  createRule,
  isRecord,
} from './shared/helpers.js';
export { createFinancialEvidence } from './shared/impact.js';
export type {
  AwsCloudFrontDistribution,
  AwsCloudFrontDistributionRequestActivity,
  AwsCloudTrailTrail,
  AwsCloudWatchLogGroup,
  AwsCloudWatchLogGroupRecentStreamActivity,
  AwsCloudWatchLogStream,
  AwsConfigRecordingFrequencyReview,
  AwsConfigRecordingModeOverride,
  AwsCostAnomalyMonitor,
  AwsCostGuardrailBudget,
  AwsCostGuardrailBudgetSpend,
  AwsCostOptimizationHubAutoScalingConfiguration,
  AwsCostOptimizationHubAutoScalingUpgradeConfiguration,
  AwsCostOptimizationHubComputeConfiguration,
  AwsCostOptimizationHubDbConfiguration,
  AwsCostOptimizationHubDynamoDbReservationConfiguration,
  AwsCostOptimizationHubEbsUpgradeConfiguration,
  AwsCostOptimizationHubEc2ReservationConfiguration,
  AwsCostOptimizationHubEc2UpgradeConfiguration,
  AwsCostOptimizationHubElastiCacheReservationConfiguration,
  AwsCostOptimizationHubGravitonConfiguration,
  AwsCostOptimizationHubGravitonRecommendation,
  AwsCostOptimizationHubIdleRecommendation,
  AwsCostOptimizationHubInstanceConfiguration,
  AwsCostOptimizationHubMemoryDbReservationConfiguration,
  AwsCostOptimizationHubOpenSearchReservationConfiguration,
  AwsCostOptimizationHubRdsReservationConfiguration,
  AwsCostOptimizationHubRdsStorageUpgradeConfiguration,
  AwsCostOptimizationHubRdsUpgradeConfiguration,
  AwsCostOptimizationHubRecommendation,
  AwsCostOptimizationHubRedshiftReservationConfiguration,
  AwsCostOptimizationHubReservationConfiguration,
  AwsCostOptimizationHubReservationRecommendation,
  AwsCostOptimizationHubRightsizingConfigurationMap,
  AwsCostOptimizationHubRightsizingRecommendation,
  AwsCostOptimizationHubSavingsPlansRecommendation,
  AwsCostOptimizationHubServiceConfiguration,
  AwsCostOptimizationHubUpgradeRecommendation,
  AwsCostOptimizationHubVolumeConfiguration,
  AwsCostUsage,
  AwsDiscoveredResource,
  AwsDiscoveryCatalog,
  AwsDynamoDbAutoscaling,
  AwsDynamoDbTable,
  AwsDynamoDbTableUtilization,
  AwsEbsSnapshot,
  AwsEbsVolume,
  AwsEc2ElasticIp,
  AwsEc2Instance,
  AwsEc2InstanceUtilization,
  AwsEc2LoadBalancer,
  AwsEc2LoadBalancerRequestActivity,
  AwsEc2NatGatewayActivity,
  AwsEc2ReservedInstance,
  AwsEc2TargetGroup,
  AwsEc2TransitGatewayVpcAttachmentActivity,
  AwsEc2VpcEndpointActivity,
  AwsEcrRepository,
  AwsEcsCluster,
  AwsEcsClusterMetric,
  AwsEcsContainerInstance,
  AwsEcsService,
  AwsEcsServiceAutoscaling,
  AwsEksNodegroup,
  AwsElastiCacheCluster,
  AwsElastiCacheClusterActivity,
  AwsElastiCacheReservedNode,
  AwsEmrCluster,
  AwsEmrClusterMetric,
  AwsKmsAliasPatternGroup,
  AwsKmsKeyChurnReview,
  AwsKmsKeyUsage,
  AwsKmsKeyUsageEvidence,
  AwsLambdaFunction,
  AwsLambdaFunctionMetric,
  AwsLambdaMemoryAssessment,
  AwsLambdaMemoryRecommendation,
  AwsRdsInstance,
  AwsRdsInstanceActivity,
  AwsRdsInstanceCpuMetric,
  AwsRdsReservedInstance,
  AwsRdsSnapshot,
  AwsRedshiftCluster,
  AwsRedshiftClusterMetric,
  AwsRedshiftReservedNode,
  AwsResourceProperty,
  AwsRoute53HealthCheck,
  AwsRoute53Record,
  AwsRoute53Zone,
  AwsS3BucketAnalysis,
  AwsS3BucketAnalysisFlags,
  AwsSageMakerEndpointActivity,
  AwsSageMakerNotebookInstance,
  AwsSageMakerSavingsPlansCoverage,
  AwsSecretsManagerSecret,
  AwsStaticCloudFrontDistribution,
  AwsStaticCloudWatchLogGroup,
  AwsStaticDynamoDbAutoscaling,
  AwsStaticDynamoDbTable,
  AwsStaticEbsVolume,
  AwsStaticEc2ElasticIp,
  AwsStaticEc2Instance,
  AwsStaticEc2VpcEndpoint,
  AwsStaticEcrRepository,
  AwsStaticEcsService,
  AwsStaticEcsServiceAutoscaling,
  AwsStaticEksNodegroup,
  AwsStaticElastiCacheCluster,
  AwsStaticEmrCluster,
  AwsStaticLambdaFunction,
  AwsStaticRdsInstance,
  AwsStaticRedshiftCluster,
  AwsStaticRoute53HealthCheck,
  AwsStaticRoute53Record,
  AwsStaticS3BucketAnalysis,
  AwsUntaggedResource,
  CloudProvider,
  DiscoveryDatasetKey,
  DiscoveryDatasetMap,
  EvidenceProvenance,
  FinancialEvidence,
  Finding,
  FindingImpact,
  FindingMatch,
  FindingRecommendation,
  IaCResource,
  IaCSuppression,
  ImpactPeriod,
  ImpactUnknownReason,
  ImpactWindow,
  LiveEvaluationContext,
  LiveEvaluationCoverage,
  RecommendationIdentity,
  Rule,
  ScanSource,
  Severity,
  Source,
  SourceLocation,
  StaticDatasetKey,
  StaticDatasetMap,
  StaticEvaluationContext,
} from './shared/metadata.js';
export { LiveResourceBag, SEVERITIES, StaticResourceBag } from './shared/metadata.js';
export {
  compareRecommendationMatches,
  createRecommendationComparator,
  createRecommendationMatch,
  deduplicateRecommendationMatches,
  getRecommendationIdentity,
} from './shared/recommendation.js';
