// Intent: expose rule packs, presets, and metadata contracts for SDK and users.
// TODO(cloudburn): publish stable docs for custom rule pack authoring.
export { awsRules } from './aws/index.js';
export { azureRules } from './azure/index.js';
export { gcpRules } from './gcp/index.js';
export { awsCorePreset } from './presets/aws-core.js';
export {
  createFinding,
  createFindingMatch,
  createRule,
  createStaticFindingMatch,
  isRecord,
  toRuleIds,
} from './shared/helpers.js';
export type {
  AwsCloudFrontDistribution,
  AwsCloudFrontDistributionRequestActivity,
  AwsCloudTrailTrail,
  AwsCloudWatchLogGroup,
  AwsCloudWatchLogGroupRecentStreamActivity,
  AwsCloudWatchLogStream,
  AwsCostAnomalyMonitor,
  AwsCostGuardrailBudget,
  AwsCostGuardrailBudgetSpend,
  AwsCostUsage,
  AwsDiscoveredResource,
  AwsDiscoveryCatalog,
  AwsDynamoDbAutoscaling,
  AwsDynamoDbTable,
  AwsDynamoDbTableUtilization,
  AwsEbsSnapshot,
  AwsEbsVolume,
  AwsEc2ElasticIp,
  AwsEc2Instance,
  AwsEc2InstanceUtilization,
  AwsEc2LoadBalancer,
  AwsEc2LoadBalancerRequestActivity,
  AwsEc2NatGatewayActivity,
  AwsEc2ReservedInstance,
  AwsEc2TargetGroup,
  AwsEc2VpcEndpointActivity,
  AwsEcrRepository,
  AwsEcsCluster,
  AwsEcsClusterMetric,
  AwsEcsContainerInstance,
  AwsEcsService,
  AwsEcsServiceAutoscaling,
  AwsEksNodegroup,
  AwsElastiCacheCluster,
  AwsElastiCacheClusterActivity,
  AwsElastiCacheReservedNode,
  AwsEmrCluster,
  AwsEmrClusterMetric,
  AwsLambdaFunction,
  AwsLambdaFunctionMetric,
  AwsLambdaMemoryRecommendation,
  AwsRdsInstance,
  AwsRdsInstanceActivity,
  AwsRdsInstanceCpuMetric,
  AwsRdsReservedInstance,
  AwsRdsSnapshot,
  AwsRedshiftCluster,
  AwsRedshiftClusterMetric,
  AwsRedshiftReservedNode,
  AwsResourceProperty,
  AwsRoute53HealthCheck,
  AwsRoute53Record,
  AwsRoute53Zone,
  AwsS3BucketAnalysis,
  AwsS3BucketAnalysisFlags,
  AwsSageMakerEndpointActivity,
  AwsSageMakerNotebookInstance,
  AwsSecretsManagerSecret,
  AwsStaticCloudFrontDistribution,
  AwsStaticCloudWatchLogGroup,
  AwsStaticDynamoDbAutoscaling,
  AwsStaticDynamoDbTable,
  AwsStaticEbsVolume,
  AwsStaticEc2ElasticIp,
  AwsStaticEc2Instance,
  AwsStaticEc2VpcEndpoint,
  AwsStaticEcrRepository,
  AwsStaticEcsService,
  AwsStaticEcsServiceAutoscaling,
  AwsStaticEksNodegroup,
  AwsStaticElastiCacheCluster,
  AwsStaticEmrCluster,
  AwsStaticLambdaFunction,
  AwsStaticRdsInstance,
  AwsStaticRedshiftCluster,
  AwsStaticRoute53HealthCheck,
  AwsStaticRoute53Record,
  AwsStaticS3BucketAnalysis,
  AwsUntaggedResource,
  CloudProvider,
  DiscoveryDatasetKey,
  DiscoveryDatasetMap,
  Finding,
  FindingMatch,
  IaCResource,
  IaCSuppression,
  LiveEvaluationContext,
  Rule,
  ScanSource,
  Severity,
  Source,
  SourceLocation,
  StaticDatasetKey,
  StaticDatasetMap,
  StaticEvaluationContext,
} from './shared/metadata.js';
export { LiveResourceBag, SEVERITIES, StaticResourceBag } from './shared/metadata.js';
